/* jQuery router plugin v0.5.3 */
(function(c){var d={put:function(a,b){(b||window).location.hash=this.encoder(a)},get:function(a){a=(a||window).location.hash.replace(/^#/,"");try{return c.browser.mozilla?a:decodeURIComponent(a)}catch(b){return a}},encoder:encodeURIComponent},f={id:"__jQuery_history",init:function(){var a='<iframe id="'+this.id+'" style="display:none" src="javascript:false;" />';c("body").prepend(a);return this},_document:function(){return c("#"+this.id)[0].contentWindow.document},put:function(a){var b=this._document();
b.open();b.close();d.put(a,b)},get:function(){return d.get(this._document())}},l={base:{callback:void 0,type:void 0,check:function(){},load:function(){},init:function(a,k){var h;h=c.extend({unescape:!1},k||{});var f=h.unescape;if(!0===f)h=function(a){return a};else{if(h="string"==typeof f){h=f.split("");var l=RegExp(c.map(h,encodeURIComponent).join("|"),"ig");h=f=function(a){return a.replace(l,decodeURIComponent)}}h=h||"function"==typeof f?function(a){return f(encodeURIComponent(a))}:encodeURIComponent}d.encoder=
h;b.callback=a;b._options=k;b._init()},_init:function(){},_options:{}},timer:{_appState:void 0,_init:function(){var a=d.get();b._appState=a;b.callback(a);setInterval(b.check,100)},check:function(){var a=d.get();a!=b._appState&&(b._appState=a,b.callback(a))},load:function(a){a!=b._appState&&(d.put(a),b._appState=a,b.callback(a))}},iframeTimer:{_appState:void 0,_init:function(){var a=d.get();b._appState=a;f.init().put(a);b.callback(a);setInterval(b.check,100)},check:function(){var a=f.get(),c=d.get();
c!=a&&(c==b._appState?(b._appState=a,d.put(a),b.callback(a)):(b._appState=c,f.put(c),b.callback(c)))},load:function(a){a!=b._appState&&(d.put(a),f.put(a),b._appState=a,b.callback(a))}},hashchangeEvent:{_init:function(){b.callback(d.get());c(window).bind("hashchange",b.check)},check:function(){b.callback(d.get())},load:function(a){d.put(a)}}},b=c.extend({},l.base);b.type=c.browser.msie&&(8>c.browser.version||8>document.documentMode)?"iframeTimer":"onhashchange"in window?"hashchangeEvent":"timer";c.extend(b,
l[b.type]);c.history=b})(jQuery);
(function(c,d){c[d]=function(b,j,r){m();b=b instanceof RegExp?new h(b,j,r):"function"==typeof b?new v(b,j):"object"==typeof b?new w(b,j):new u(b,j,r);a.push(b);j=c[d].last();l&&b.test(j)&&(g&&(g.leave(),g=null),c[d].pop(),b.exec()&&(g=b),k.push(j));return c};var f,l=!0,b=null;c[d]=c.extend(c[d],{hasHistory:function(){return 0<k.length},last:function(){return c[d].hasHistory()?k[k.length-1]:""},pop:function(){return k.pop()},remove:function(b){if(0==arguments.length)return a=[],g=null,c;c(arguments).each(function(b,
c){for(var e,q=[];e=a.pop();)e.leave==c&&(e.leave=null,g==e&&(g=null)),e.remove(c)?g==e&&(g=null):q.push(e);a=q});return c},stop:function(){l=!1;b=null;return this},start:function(){l=!0;p();n(location.hash.replace(/^#/,""));return this},leave:function(a){if("function"!==typeof a)throw Error("Invalid leave callback. Function required!");g=new x(a);return c},newChangeCallback:function(){f=function(c){if(l&&b!==c&&f===arguments.callee){b=c;g&&(g.leave(),g=null);for(var j=a.length-1,d=!1;!d&&0<=j;){if(d=
a[j].test(c)){var e=a[j];e.exec()&&(g=e)}j--}k.push(c)}};m=function(){};return f},restoreChangeCallback:function(){f=n;m=p;a.length&&m()}});var a=[],k=[],h=function(a,b,c){var e,d;this.test=function(b){return(e=a.exec(b))&&!0};this.exec=function(){d=b.apply(null,e)||c;return"function"==typeof d};this.leave=function(){d.apply(null,e)};this.remove=function(e){if(a==e||b==e)return!0;c==e&&delete c;d==e&&(d=null);return!1}},u=function(a,b,c){this.test=function(b){return a==b};this.exec=function(){this.leave=
b()||c;return"function"==typeof this.leave};this.remove=function(e){if(a==e||b==e)return!0;c==e&&delete c;return!1}},w=function(a,b){var d;this.test=function(b){return(d=a[b])&&!0};this.exec=function(){this.leave=d()||b;return"function"==typeof this.leave};this.remove=function(e){if(a==e)return!0;do{var f=!1;c.each(a,function(b,a){if(b==e||a==e)return f=b,!1});f&&delete a[f]}while(f);if(d==e)return!0;b==e&&delete b;return!1}},v=function(b,a){var c;this.test=function(a){return(c=b(a))&&!0};this.exec=
function(){this.leave=c()||a;return"function"==typeof this.leave};this.remove=function(c){if(b==c)return!0;a==c&&delete a;return!1}},x=function(a){this.test=function(){return!1};this.exec=function(){return!1};this.leave=function(){a();c[d].remove(a)};this.remove=function(b){return a==b}},g,n=c[d].newChangeCallback(),p,s=!1,t=function(){c.history.init(n)},m=p=function(){!s&&n===f&&(s=!0,c.browser.msie?c(t):t())}})(jQuery,"router");